const items = [
    {
        id: '001',
        image: '../Images/Items/t1.jpg',
        company: 'Aero Armour',
        item_name: 'Typography Printed Pure Cotton T-shirt',
        original_price: 1499,
        current_price: 799,
        discount_percentage: 53,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 3.9,
            count: 32,
        },
    },
    {
        id: '002',
        image: '../Images/Items/s1.jpg',
        company: 'Roadster',
        item_name: 'Men White Opaque Cotton Linen Casual Shirt',
        original_price: 1999,
        current_price: 519,
        discount_percentage: 74,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.1,
            count: 1400,
        },
    },
    {
        id: '003',
        image: '../Images/Items/s2.jpg',
        company: 'Mast & Harbour',
        item_name: 'Pullover Sweatshirt',
        original_price: 1699,
        current_price: 934,
        discount_percentage: 45,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.3,
            count: 123,
        },
    },
    {
        id: '004',
        image: '../Images/Items/j1.jpg',
        company: 'Reebok',
        item_name: 'Core Track Training Jacket',
        original_price: 2799,
        current_price: 1679,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.1,
            count: 87,
        },
    },
    {
        id: '005',
        image: '../Images/Items/c1.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Grey Solid Single-Breasted Blazer',
        original_price: 4849,
        current_price: 1551,
        discount_percentage: 68,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 3.3,
            count: 48,
        },
    },
    {
        id: '006',
        image: '../Images/Items/je1.jpg',
        company: 'Levis',
        item_name: 'Men 511 Slim Fit Light Fade Stretchable Jeans',
        original_price: 4299,
        current_price: 1934,
        discount_percentage: 55,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.3,
            count: 95,
        },
    },
    {
        id: '007',
        image: '../Images/Items/f1.jpg',
        company: 'AD By Arvind',
        item_name: 'Men Mid-Rise Slim Fit Trousers',
        original_price: 1899,
        current_price: 1234,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4,
            count: 189,
        },
    },
    {
        id: '008',
        image: '../Images/Items/sh2.jpg',
        company: 'ASIAN',
        item_name: 'Men Mesh Running Non-Marking Shoes',
        original_price: 1199,
        current_price: 899,
        discount_percentage: 25,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.1,
            count: 2000,
        },
    },
    {
        id: '009',
        image: '../Images/Items/sh1.jpg',
        company: 'U.S. Polo Assn.',
        item_name: 'Men Brown MONTON 4.0 Sneakers',
        original_price: 2999,
        current_price: 1799,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        seller: 'Beyond Trends',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
];